### ISSUE TITLE
Error returned when executing script: "UnicodeDecodeError"

### ISSUE THREAD

**Issue by tmpduarte** [nst/objc_strings#13]
When executing the script I get the following in the command line:
Traceback (most recent call last):
  File "./scripts/build/objc_strings.py", line 207, in <module>
    main()
  File "./scripts/build/objc_strings.py", line 204, in main
    show_untranslated_keys_in_project(project_path)
  File "./scripts/build/objc_strings.py", line 175, in show_untranslated_keys_in_project
    keys_set_in_strings = keys_set_in_strings_file_at_path(p)
  File "./scripts/build/objc_strings.py", line 97, in keys_set_in_strings_file_at_path
    for s in f:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 684, in next
    return self.reader.next()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 615, in next
    line = self.readline()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 530, in readline
    data = self.read(readsize, firstline=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xdf in position 8: invalid continuation byte

**Comment by andres-ciano** [comment]
Working with both the --exclude-dirs option, I'm getting all keys as missing. Even ignoring dirs within the code so the script runs I cannot get it to properly filter existing keys from missing ones.
Any ideas?

**Comment by purrrminator** [comment]
My error:

Traceback (most recent call last):
  File "/Users/andreykadochnikov/Documents/XCODE PROJECTS/walletkeeper/objc_strings.py", line 212, in <module>
    main()
  File "/Users/andreykadochnikov/Documents/XCODE PROJECTS/walletkeeper/objc_strings.py", line 209, in main
    show_untranslated_keys_in_project(project_path, options.exclude_dirs)
  File "/Users/andreykadochnikov/Documents/XCODE PROJECTS/walletkeeper/objc_strings.py", line 175, in show_untranslated_keys_in_project
    keys_set_in_strings = keys_set_in_strings_file_at_path(p)
  File "/Users/andreykadochnikov/Documents/XCODE PROJECTS/walletkeeper/objc_strings.py", line 95, in keys_set_in_strings_file_at_path
    for s in f:
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 684, in next
    return self.reader.next()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 615, in next
    line = self.readline()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 530, in readline
    data = self.read(readsize, firstline=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/codecs.py", line 477, in read
    newchars, decodedbytes = self.decode(data, self.errors)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xd3 in position 8: invalid continuation byte
Command /bin/sh failed with exit code 1

I'm executing this script: ```
"${SRCROOT}/objc_strings.py" --exclude-dirs=['Build','Pods','Vendor']
```
